#!/usr/bin/env python3
"""Translate SOC_ger7 Danish criminal-offense descriptions to English.

GER7 codes are Danish-specific (they encode entries from Danish police/justice
registers, keyed by the offense sections of Danish law), so there is no
authoritative international English translation. This script produces
English labels by substring substitution against a Danish legal-stem
dictionary plus a handful of whole-phrase translations for the repeated
boilerplate patterns.

It only writes description_en (never description_en_official — there is no
authoritative international equivalent). Descriptions that partially resist
translation (i.e. Danish characters remain after substitution) are flagged
on stderr so they can be hand-corrected.

Usage:
    python3 scripts/translate_soc_ger7.py [--dry-run]
"""
import argparse
import csv
import re
import sys

MASTER_PATH = "MASTER_CATEGORY_MAPPINGS.csv"

# --- Whole-phrase replacements (applied first, case-insensitive whole match) -
PHRASES = {
    "Alkolåsordning": "Alcohol interlock order",
    "Anvisninger, ikke efterkommet": "Instructions not complied with",
    "Anpartsselskabsloven": "Private Limited Companies Act",
    "Aktieselskabsloven": "Public Limited Companies Act",
    "Arbejderbeskyttelseslovgivningen": "Occupational safety legislation",
    "Arbejdsskadeforsikringsloven": "Workers' Compensation Insurance Act",
    "Asylsøger ej tilbagesendt til andet land":
        "Asylum seeker not returned to another country",
    "Bagvaskelse": "Defamation",
    "Bank- og sparekasselov": "Banking and Savings Bank Act",
    "Bemandingslov": "Ship manning law",
    "Begæring om advarsel": "Request for warning",
    "Bigami, den gifte person": "Bigamy, the married person",
    "Bestikkelse af offentlig myndighed": "Bribery of public authority",
    "Borgerligt ombud": "Civic duty",
    "Bortfjernelse af folketælling": "Removal of census data",
    "Dødsstraf": "Death penalty",
    "Falske erklæringer": "False declarations",
    "Falsk anklage": "False accusation",
    "Falsk forklaring": "False testimony",
    "Falskmøntneri": "Counterfeiting",
    "Ildspåsættelse": "Arson",
    "Mandatsvig": "Breach of trust",
    "Manddrab": "Homicide",
    "Trusler": "Threats",
    "Tilhold": "Restraining order",
    "Skyldnersvig": "Debtor fraud",
    "Grov vold": "Aggravated violence",
    "Simpel vold": "Simple violence",
    "Vold": "Violence",
    "Røveri": "Robbery",
    "Afpresning": "Extortion",
    "Bedrageri": "Fraud",
    "Blufærdighedskrænkelse": "Indecent exposure",
    "Voldtægt": "Rape",
    "Forsøg": "Attempt",
    "Medvirken": "Accessory / complicity",
    "Ulovlig tvang": "Unlawful coercion",
    "Uagtsomt manddrab": "Negligent homicide",
    "Uagtsom legemsbeskadigelse": "Negligent bodily harm",
    "Grov uagtsomhed": "Gross negligence",
    "Antibiotikalovgivningen": "Antibiotics legislation",
    "Brandstiftelse": "Arson",
    "Hæleri": "Receiving stolen goods",
    "Særdeles farlige våben": "Particularly dangerous weapons",
    "Andre strafferetslige særlove": "Other penal special laws",
    "Andre sundheds- og sociallove": "Other health and social laws",
    "Bekendtgørelse om bedriftssundhedstjeneste":
        "Regulation on occupational health service",
    "Bekendtgørelse om radio- og fjernsynsafgift":
        "Regulation on radio and television fees",
}

# --- Stem substitutions (applied to whatever isn't covered by PHRASES) ------
# Order matters: longer/more-specific stems first.
STEMS = [
    # Compound law-name words (most specific first)
    ("Færdselslovsovertrædelse", "Road Traffic Act violation"),
    ("Færdselsloven", "Road Traffic Act"),
    ("Hastighedsovertrædelse", "Speeding violation"),
    ("hastighedsovertrædelse", "speeding violation"),
    ("Vigepligt, ubetinget", "Yield obligation, unconditional"),
    ("Vigepligt", "Yield obligation"),
    ("vigepligt", "yield obligation"),
    ("afmærkning", "road marking"),
    ("Hastighed", "Speed"),
    ("hastighed", "speed"),
    ("Befordring af barn", "Transport of child"),
    ("Befordring af børn", "Transport of children"),
    ("sidepladser", "side seats"),
    ("siddepladser", "seats"),
    ("særligt sikkerhedsudstyr", "special safety equipment"),
    ("Udlændingeloven", "Aliens Act"),
    ("Ordensbekendtgørelsen", "Public Order Regulation"),
    ("Affaldsbekendtgørelsen", "Waste Regulation"),
    ("Registreringsbekendtgørelse", "Registration Regulation"),
    ("Sikkerhedssele", "Seat belt"),
    ("hastighedsovertrædelse", "speeding violation"),
    ("færdselstavle", "traffic sign"),
    ("Mobiltelefon, brug af håndholdt", "Mobile phone, handheld use"),
    ("Arbejdstilsynet", "Working Environment Authority"),
    ("Bekendtgørelse om", "Regulation on"),
    ("Lov om", "Act on"),
    ("Love vedrørende", "Laws regarding"),
    ("love vedrørende", "laws regarding"),
    ("love vedr.", "laws regarding"),
    ("Lovgivning om", "Legislation on"),
    ("lovgivning", "legislation"),
    # Action / offence verbs
    ("Anden kønslig omgang med", "Other sexual contact with"),
    ("Andet seksuelt forhold med", "Other sexual relation with"),
    ("Anden kønslig omgang ved", "Other sexual contact through"),
    ("Andet seksuelt forhold ved", "Other sexual relation through"),
    ("kønslig omgang", "sexual contact"),
    ("seksuelt forhold", "sexual relation"),
    ("Blodskam i øvrigt", "Incest, other"),
    ("Blodskam", "Incest"),
    ("Brugstyveri", "Joyriding / unauthorised use"),
    ("Indbrud i bank", "Burglary in bank"),
    ("Indbrud", "Burglary"),
    ("Tyveri", "Theft"),
    # Voldtægt BEFORE Vold so the stem doesn't get clobbered
    ("Voldtægt", "Rape"),
    ("voldtægt", "rape"),
    ("Særlig grov vold", "Particularly aggravated violence"),
    ("Grov vold", "Aggravated violence"),
    ("Simpel vold", "Simple violence"),
    ("Vold", "Violence"),
    ("vold", "violence"),
    ("Røveri", "Robbery"),
    ("røveri", "robbery"),
    ("Afpresning", "Extortion"),
    ("Bedrageri", "Fraud"),
    ("Underslæb", "Embezzlement"),
    ("Dokumentfalsk", "Document forgery"),
    ("Falsk", "False"),
    ("Brandstiftelse", "Arson"),
    ("Hæleri", "Receiving stolen goods"),
    ("Manddrab", "Homicide"),
    ("Drab", "Killing"),
    ("Voldtægt", "Rape"),
    ("Blufærdighedskrænkelse", "Indecent exposure"),
    ("Bestikkelse", "Bribery"),
    ("Forførelse", "Seduction"),
    ("Tilsnigelse", "Deception"),
    ("Uagtsomt", "Negligent"),
    ("uagtsomt", "negligent"),
    ("Uagtsom", "Negligent"),
    ("Groft", "Grave"),
    ("Grov", "Aggravated"),
    ("grov", "aggravated"),
    # Subjects / objects
    ("børn under 12 år", "children under 12 years"),
    ("børn under 15 år", "children under 15 years"),
    ("barn under 12 år", "child under 12 years"),
    ("barn under 15 år", "child under 15 years"),
    ("institutionsanbragt", "person placed in institution"),
    ("plejebarn", "foster child"),
    ("stedbarn", "stepchild"),
    ("mellem søskende", "between siblings"),
    ("psykisk abnormitet", "mental abnormality"),
    ("hjælpeløs tilstand", "helpless state"),
    ("legemsbeskadigelse", "bodily harm"),
    ("legemsbesk.", "bodily harm"),
    # Drugs / alcohol / substances
    ("Spiritus, salg til unge", "Alcohol, sale to minors"),
    ("Alkohol, salg til unge", "Alcohol, sale to minors"),
    ("Spirituskørsel", "Drunk driving"),
    ("Spiritus", "Alcohol"),
    ("Narkotika", "Narcotics"),
    ("Stoffer", "Substances"),
    # Weapons
    ("Særligt farlige våben", "Particularly dangerous weapons"),
    ("Særligt farlige", "Particularly dangerous"),
    ("Eksplosivstoffer", "Explosive substances"),
    ("Eksplosive stoffer", "Explosive substances"),
    ("Våben", "Weapons"),
    # Connectives / boilerplate
    ("særlig skærpende omstændigheder", "particularly aggravating circumstances"),
    ("skærpende omstændigheder", "aggravating circumstances"),
    ("overtrædelse af forbud mod", "violation of prohibition against"),
    ("Overtrædelse af", "Violation of"),
    ("overtrædelse", "violation"),
    ("uretmæssig", "unlawful"),
    ("uberettiget", "unauthorised"),
    ("i øvrigt", "otherwise"),
    ("i.a.n.", "NEC"),
    ("mv.", "etc."),
    ("m.v.", "etc."),
    ("ifm.", "in connection with"),
    ("ifølge", "according to"),
    ("vedr.", "regarding"),
    ("FUH.", "Traffic accident"),
    ("ATK", "ATK"),  # Automatic Traffic Control — abbreviation kept
    ("(klip)", "(penalty points)"),
    # Specific nouns/phrases
    ("Meddelt advarsel", "Warning issued"),
    ("meddelt advarsel", "warning issued"),
    ("påbud", "directive"),
    ("betleri", "begging"),
    ("Betleri", "Begging"),
    ("asylsøger", "asylum seeker"),
    ("Asylsøger", "Asylum seeker"),
    ("bank- og sparekasselov", "Banking and Savings Bank Act"),
    ("selskabslovgivning", "company legislation"),
    ("firmalovgivning", "firm legislation"),
    ("selskabs- og firma", "company and firm"),
    ("arbejdsløshedskasse", "unemployment fund"),
    ("kontokort", "account card"),
    ("dankort", "debit card"),
    ("checks", "cheques"),
    ("check", "cheque"),
    ("overtræk", "overdraft"),
    ("egen konto", "own account"),
    ("stjålne", "stolen"),
    ("stjålet", "stolen"),
    # Simple particles / inflections
    ("indenfor", "within"),
    ("udenfor", "outside"),
    ("vedrørende", "regarding"),
    ("herunder", "including"),
    ("heraf", "thereof"),
    ("samt", "and"),
    (" og ", " and "),
    (" af ", " of "),
    (" til ", " to "),
    (" ved ", " by "),
    (" med ", " with "),
    (" eller ", " or "),
    (" mod ", " against "),
    (" for ", " for "),
    # Common domain nouns
    ("udlændinge", "foreigners"),
    ("dyretransport", "animal transport"),
    ("Dyretransport", "Animal transport"),
    # Keep longest "køre-*" compounds first to avoid stem corruption
    ("Motorkøretøj", "Motor vehicle"),
    ("motorkøretøj", "motor vehicle"),
    ("Køre-hviletidsregler", "Driving and rest-time rules"),
    ("køre-hviletidsregler", "driving and rest-time rules"),
    ("Kørselsforbud", "Driving ban"),
    ("kørsel", "driving"),
    ("Kørsel", "Driving"),
    ("køretøjer", "vehicles"),
    ("Køretøjer", "Vehicles"),
    ("køretøjets", "vehicle's"),
    ("køretøj", "vehicle"),
    ("Køretøj", "Vehicle"),
    ("køretur", "drive"),
    ("Overhaling", "Overtaking"),
    ("overhaling", "overtaking"),
    # Punishment / case words
    ("sag", "case"),
    ("dom", "judgment"),
    ("afgørelse", "decision"),
    # Additional common Danish terms  (batch 2)
    ("Motorfører", "Motor-vehicle driver"),
    ("motorfører", "motor-vehicle driver"),
    ("spirituspåvirket", "under the influence of alcohol"),
    ("Spirituspåvirket", "Under the influence of alcohol"),
    ("Kørselsforbud", "Driving ban"),
    ("Kørekort", "Driving licence"),
    ("kørekort", "driving licence"),
    ("førerret", "driving licence"),
    ("Førerret", "Driving licence"),
    ("Fører af", "Driver of"),
    ("fører af", "driver of"),
    (" på ", " on "),
    (" år", " years"),
    ("færdselsuheld", "traffic accident"),
    ("Færdselsuheld", "Traffic accident"),
    ("sædelighedsforbrydelse", "sexual offence"),
    ("Sædelighedsforbrydelse", "Sexual offence"),
    ("sædelighed", "sexual morality"),
    ("Blufærdighedskrænkelse", "Indecent exposure"),
    ("Ærekrænkelse", "Defamation"),
    ("ærekrænkelse", "defamation"),
    ("Krænkelse", "Violation"),
    ("krænkelse", "violation"),
    ("uanstændighed", "indecency"),
    ("Uanstændighed", "Indecency"),
    ("forførelse", "seduction"),
    ("Forførelse", "Seduction"),
    ("beføling", "groping"),
    ("hærværk", "vandalism"),
    ("Hærværk", "Vandalism"),
    ("sprængstof", "explosive"),
    ("Sprængstof", "Explosive"),
    ("Fornærmelig", "Insulting"),
    ("fornærmelig", "insulting"),
    ("Overtrådt", "Violated"),
    ("overtrådt", "violated"),
    ("pålagt", "imposed"),
    ("pålæg", "order"),
    ("Pålæg", "Order"),
    ("nærmeste", "nearest"),
    ("Nærmeste", "Nearest"),
    ("øvrige", "other"),
    ("Øvrige", "Other"),
    ("særlig", "particularly"),
    ("Særligt", "Particularly"),
    ("særligt", "particularly"),
    ("første", "first"),
    ("Første", "First"),
    ("anden", "other"),
    ("Anden", "Other"),
    ("andet", "other"),
    ("Andet", "Other"),
    ("høj", "high"),
    ("Høj", "High"),
    ("følge", "consequence"),
    ("Følge", "Consequence"),
    ("lønmodtagere", "employees"),
    ("Lønmodtagere", "Employees"),
    ("lønmodtager", "employee"),
    ("chauffør", "driver"),
    ("Chauffør", "Driver"),
    ("båd", "boat"),
    ("Båd", "Boat"),
    ("værelse", "room"),
    ("kælder", "basement"),
    ("Hjælp", "Help"),
    ("hjælp", "help"),
    ("mærke", "mark"),
    ("svømmehal", "swimming pool"),
    ("idrætsanlæg", "sports facility"),
    ("Udgået", "Discontinued"),
    ("udgået", "discontinued"),
    # Connector and particle fixes
    (" uden ", " without "),
    ("uden ", "without "),
    (" gult ", " yellow "),
    ("/gult", "/yellow"),
    (" mod ", " against "),
    (" imod ", " against "),
    ("Lyssignal", "Traffic light"),
    ("lyssignal", "traffic light"),
    ("Håndholdt", "Handheld"),
    ("teleudstyr", "telecommunications equipment"),
    ("Spærrelinjer", "Solid lines"),
    ("spærrelinjer", "solid lines"),
    ("overskridelse", "crossing"),
    ("Autorisation", "Authorisation"),
    ("autorisation", "authorisation"),
    ("sundhedspersoner", "health professionals"),
    ("sundhedsperson", "health professional"),
    ("læger", "doctors"),
    ("læge", "doctor"),
    ("særlovgivning", "special legislation"),
    ("særlegislation", "special legislation"),
    ("planlægning", "planning"),
    ("Planlægning", "Planning"),
    ("uorden", "disorder"),
    ("Uorden", "Disorder"),
    ("bøger", "books"),
    ("regnskabsbøger", "accounting books"),
    ("forretningsmæssig", "business-like"),
    ("forretningsbøger", "business books"),
    # Typos / variants
    ("Motorkørertøj", "Motor vehicle"),
    ("motorkørertøj", "motor vehicle"),
    ("køre-hviletid", "driving and rest time"),
    ("Køre-hviletid", "Driving and rest time"),
    # Batch 5: remaining Danish laws & specific terms
    ("Ferieloven", "Holiday Act"),
    ("Retsplejeloven", "Administration of Justice Act"),
    ("Lægeloven", "Medical Practitioners Act"),
    ("Værnepligtsloven", "Conscription Act"),
    ("Jernbaneloven", "Railway Act"),
    ("Søloven", "Maritime Act"),
    ("Toldloven", "Customs Act"),
    ("Luftfartsloven", "Civil Aviation Act"),
    ("Næringsloven", "Trades Act"),
    ("Folkeregisterlov", "National Register Act"),
    ("Kemikalieloven", "Chemicals Act"),
    ("Militære straffelov", "Military Criminal Code"),
    ("militær straffelov", "military criminal code"),
    ("Farlig beruselse", "Dangerous intoxication"),
    ("beruselse", "intoxication"),
    ("Databedrageri", "Data fraud"),
    ("Pengefalsk", "Currency counterfeiting"),
    ("Intellektuelt falsk", "Intellectual forgery"),
    ("Terrorisme", "Terrorism"),
    ("terrorisme", "terrorism"),
    ("Åger", "Usury"),
    ("åger", "usury"),
    ("Racediskrimination", "Racial discrimination"),
    ("racediskrimination", "racial discrimination"),
    ("Pengeskabstyveri", "Safe theft"),
    ("pengeskabstyveri", "safe theft"),
    ("Maskering, forbud mod", "Masking, prohibition of"),
    ("maskering", "masking"),
    ("forbud mod", "prohibition of"),
    ("opgive navn", "give name"),
    ("nægter", "refuses"),
    ("Syn, ikke efterkommet tilsigelse til",
     "Inspection, not complied with summons to"),
    ("tilsigelse", "summons"),
    ("Forsikring, ikke tegnet", "Insurance, not taken out"),
    ("ikke tegnet", "not taken out"),
    ("ikke brug af", "not used"),
    ("Afgiftslove for drikkevarer, tobak, benzin",
     "Excise-duty acts on beverages, tobacco, petrol"),
    ("drikkevarer", "beverages"),
    ("tobak", "tobacco"),
    ("benzin", "petrol"),
    # Partial-word fixes
    ("Lægge", "Lay"),
    ("lægge", "lay"),
    ("udførelse", "execution"),
    ("Udførelse", "Execution"),
    ("iøvrigt", "otherwise"),
    ("nattesæde", "night-time stay"),
    ("tømmerhandel", "timber shop"),
    ("ægte", "genuine"),
    ("afbrænding", "burning"),
    ("unødig", "unnecessary"),
    ("Unødig", "Unnecessary"),
    ("opnåelse", "obtainment"),
    ("Speedsbegrænser", "Speed limiter"),
    ("speedsbegrænser", "speed limiter"),
    ("Særlig", "Particular"),
    ("særlig", "particular"),
    ("møder", "meetings"),
    # Batch 4: specific whole-word Danish laws & offenses still unmatched
    ("Skattekontrolloven", "Tax Control Act"),
    ("Socialbedrageri", "Social-benefit fraud"),
    ("Fyrværkeriloven", "Fireworks Act"),
    ("Restaurationsloven", "Restaurant and Licensing Act"),
    ("Fødevareloven", "Food Act"),
    ("Jagtloven", "Hunting Act"),
    ("Landbrugsloven", "Agriculture Act"),
    ("Lægemiddelloven", "Medicines Act"),
    ("Markedsføringsloven", "Marketing Practices Act"),
    ("Rufferi", "Procuring / pimping"),
    ("Frihedsberøvelse", "Deprivation of liberty"),
    ("Bombetrusler", "Bomb threats"),
    ("bombetrusler", "bomb threats"),
    ("Telefonbomber", "Phone bombs"),
    ("telefonbomber", "phone bombs"),
    ("Rudeknusningstyveri", "Smash-and-grab theft"),
    ("rudeknusningstyveri", "smash-and-grab theft"),
    ("Styrthjelm", "Crash helmet"),
    ("styrthjelm", "crash helmet"),
    ("meddelt forbud", "prohibition issued"),
    ("Meddelt tilhold", "Restraining order issued"),
    ("ulovlig udskænkning", "unlawful serving"),
    ("udskænkning", "serving"),
    ("Manglende registrering", "Missing registration"),
    ("manglende registrering", "missing registration"),
    ("Manglende", "Missing"),
    ("manglende", "missing"),
    ("Lygteføring", "Light operation"),
    ("lygteføring", "light operation"),
    ("Gående", "Pedestrians"),
    ("gående", "pedestrians"),
    ("forpligtelser", "obligations"),
    ("overfor", "towards"),
    ("Urigtig forklaring", "False testimony"),
    ("Urigtig", "False"),
    ("pligtforhold", "duty relationship"),
    ("anmeldelse", "report"),
    ("klagemål", "complaint"),
    ("Hindring", "Obstruction"),
    ("hindring", "obstruction"),
    ("strafforfølgning", "criminal prosecution"),
    ("fuldbyrdelse", "enforcement"),
    ("værnepligtige", "conscripts"),
    ("værnepligtig", "conscript"),
    ("værnepligt", "conscription"),
    ("civilt arbejde", "civilian work"),
    ("civilt", "civilian"),
    ("Ulovlig besiddelse", "Unlawful possession"),
    ("Børnepornografi", "Child pornography"),
    ("børnepornografi", "child pornography"),
    ("bekendt med", "aware of"),
    # Batch 3: specific leftover vocabulary
    ("Forvoldt", "Caused"),
    ("forvoldt", "caused"),
    ("forsætlig", "intentional"),
    ("forsætligt", "intentionally"),
    ("forsætlige", "intentional"),
    ("rødt", "red"),
    ("gult", "yellow"),
    ("grønt", "green"),
    ("børnehave", "kindergarten"),
    ("vuggestue", "daycare"),
    ("fritidshjem", "after-school centre"),
    ("værksted", "workshop"),
    ("slæbning", "towing"),
    ("Tilkobling", "Coupling"),
    ("tilkobling", "coupling"),
    ("motorvej", "motorway"),
    ("Motorvej", "Motorway"),
    ("færdselsloven", "Road Traffic Act"),
    ("færdselslov", "Road Traffic Act"),
    ("ødelæggelse", "destruction"),
    ("Ødelæggelse", "Destruction"),
    ("segl", "seal"),
    ("mark", "mark"),
    ("Kap- og væddedriving", "Racing and betting on driving"),
    ("væddedriving", "betting driving"),
    ("væddemål", "betting"),
    ("Helleanlæg", "Traffic island"),
    ("helleanlæg", "traffic island"),
    ("knallert", "moped"),
    ("Knallert", "Moped"),
    ("knivloven", "Knife Act"),
    ("Knivloven", "Knife Act"),
    ("kniv", "knife"),
    ("Kniv", "Knife"),
    ("offentligt tilgængeligt", "publicly accessible"),
    ("tilgængeligt", "accessible"),
    ("tilgængelig", "accessible"),
    ("påhængsvehicle", "trailer"),
    ("påhængskøretøj", "trailer"),
    ("registreret", "registered"),
    ("konstruktive ændringer", "structural modifications"),
    ("ændringer", "modifications"),
    ("ændring", "modification"),
    ("speedsforøgelse", "speed increase"),
    ("Speedsforøgelse", "Speed increase"),
    ("hastighedsforøgelse", "speed increase"),
    ("omklædningsrum", "changing room"),
    ("Veterinærlegislationen", "Veterinary legislation"),
    ("veterinær", "veterinary"),
    ("Veterinær", "Veterinary"),
    ("unddragelse", "evasion"),
    ("Unddragelse", "Evasion"),
    ("forældreauthority", "parental authority"),
    ("forældremyndighed", "parental authority"),
    ("frihedsberøvet", "deprived of liberty"),
    ("Frihedsberøvet", "Deprived of liberty"),
    ("unlawful besiddelse", "unlawful possession"),
    ("besiddelse", "possession"),
    ("mobiltelefon", "mobile phone"),
    ("Karantæne", "Quarantine"),
    ("karantæne", "quarantine"),
    ("idrætsbegivenheder", "sporting events"),
    ("idrætsbegivenhed", "sporting event"),
    ("Befordring", "Transport"),
    ("flere børn end", "more children than"),
    ("børn", "children"),
    ("andre regler", "other rules"),
    ("regler", "rules"),
    ("regel", "rule"),
    ("forekomst", "occurrence"),
    ("Ikke aktiv", "Not active"),
    ("livsforsikring", "life insurance"),
    ("førlighed", "physical ability"),
    ("Første", "First"),
    ("stof", "substance"),
    ("fare", "danger"),
    ("liv", "life"),
    ("retten", "the court"),
    # Whole-word Danish law names and offense terms
    ("Dyreværnsloven", "Animal Welfare Act"),
    ("dyreværnsloven", "Animal Welfare Act"),
    ("Miljøloven", "Environment Act"),
    ("Naturbeskyttelsesloven", "Nature Conservation Act"),
    ("Politivedtægten", "Police Ordinance"),
    ("politivedtægten", "Police Ordinance"),
    ("Våbenloven", "Weapons Act"),
    ("våbenloven", "Weapons Act"),
    ("Narkotikaloven", "Narcotics Act"),
    ("Spiritusloven", "Liquor Act"),
    ("Butikstyveri", "Shoplifting"),
    ("butikstyveri", "shoplifting"),
    ("købmand", "grocer"),
    ("supermarked", "supermarket"),
    ("mejeri", "dairy"),
    ("forretninger", "shops"),
    ("forretning", "shop"),
    ("beklædning", "clothing"),
    ("skind", "hides"),
    ("fodtøj", "footwear"),
    ("Overlæs", "Overloading"),
    ("overlæs", "overloading"),
    ("totalvægt", "gross weight"),
    ("vægt", "weight"),
    ("dimensioner", "dimensions"),
    ("belæsning", "loading"),
    ("syn ikke efterkommet", "inspection not complied with"),
    ("Manglende agtpågivenhed", "Lack of attentiveness"),
    ("agtpågivenhed", "attentiveness"),
    ("Fange, flygtet", "Prisoner, escaped"),
    ("Fange", "Prisoner"),
    ("flygtet", "escaped"),
    ("Forordninger om fartskrivere", "Regulations on tachographs"),
    ("fartskrivere", "tachographs"),
    ("fartskriver", "tachograph"),
    ("Kontrolapparat", "Control apparatus"),
    ("Skydevåben", "Firearms"),
    ("skydevåben", "firearms"),
    ("våben", "weapons"),
    ("møntvaskeri", "laundromat"),
    ("værditransport", "cash-in-transit"),
    ("Miljøzone", "Environment zone"),
    ("miljøzone", "environment zone"),
    ("opløb", "gathering"),
    ("Nødspor", "Emergency lane"),
    ("Rødt lys", "Red light"),
    ("rødt lys", "red light"),
    ("igangsætning", "starting up"),
    ("pågældende", "concerning"),
    ("særdeles", "particularly"),
    ("skærpende", "aggravating"),
    ("omstændighed", "circumstance"),
    ("hæleri", "receiving stolen goods"),
    ("Fører", "Driver"),
    ("fører", "driver"),
    # General terms
    ("bedriftssundhedstjeneste", "occupational health service"),
    ("Bedriftssundhedstjeneste", "Occupational health service"),
    ("offentlig stilling", "public office"),
    ("hverv", "duty"),
    ("urigtig skriftlig erklæring", "false written declaration"),
    ("urigtig", "false"),
    ("skriftlig", "written"),
    ("erklæring", "declaration"),
    ("misbrug", "misuse"),
    ("offentlig myndighed", "public authority"),
    ("myndighed", "authority"),
    ("betalingsmiddel", "means of payment"),
    ("videregivelse", "disclosure"),
    ("anvendelse", "use"),
    ("besøgende", "visitors"),
    ("Besøgende", "Visitors"),
    ("uretmæssig medtager", "unauthorised bringing"),
    ("medtager", "bringing"),
    ("bestemte lokaler", "certain premises"),
    ("forsyninger", "utilities"),
    ("offentlige forsyninger", "public utilities"),
    ("miljø", "environment"),
    ("skatte- og afgiftslove", "tax and duty laws"),
    ("skat", "tax"),
    ("afgift", "duty"),
    ("sociallove", "social laws"),
    ("sundheds-", "health-"),
    ("sundhed", "health"),
    ("spil", "gambling"),
    ("bevilling", "licence"),
    ("næring", "trade"),
    ("jagt", "hunting"),
    ("dyr", "animals"),
    ("transport", "transport"),
    ("arbejde", "work"),
    ("Arbejdsløshed", "Unemployment"),
    ("arbejdsløshed", "unemployment"),
    ("ordensbekendtgørelse", "public order regulation"),
    ("bekendtgørelse", "regulation"),
    ("Bekendtgørelse", "Regulation"),
]

DANISH_CHARS = re.compile(r"[æøåÆØÅ]")


def translate(text: str) -> str:
    # 1) whole-phrase match
    if text in PHRASES:
        return PHRASES[text]
    # Case-insensitive whole match
    for phrase, en in PHRASES.items():
        if text.lower() == phrase.lower():
            return en
    # 2) stem substitution
    out = text
    for da, en in STEMS:
        # Case-insensitive replace while preserving sentence-initial capitalization
        # Use a simple replace (case-sensitive) to avoid corrupting compound words
        out = out.replace(da, en)
    # Light cleanup
    out = re.sub(r"\s{2,}", " ", out).strip()
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    with open(MASTER_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames)
        rows = list(reader)

    applied = 0
    leftover_danish = 0
    samples = []

    for row in rows:
        if row["category"] != "SOC_ger7":
            continue
        en_cur = row["description_en"].strip()
        # Re-translate rows whose EN still contains Danish chars (previous partial)
        # or the known-buggy 'Violencetægt' artifact.
        if en_cur and not (DANISH_CHARS.search(en_cur) or "Violencet" in en_cur):
            continue
        da = row["description_da"].strip()
        if not da:
            continue
        en = translate(da)
        if en == da:
            # Nothing translated
            continue
        row["description_en"] = en
        row["description_short"] = re.sub(r"\s*\([^)]*\)", "", en).strip()
        row["description_en_source"] = "translated"
        applied += 1
        if DANISH_CHARS.search(en):
            leftover_danish += 1
            if len(samples) < 6:
                samples.append((row["code"], da, en, "partial"))
        elif len(samples) < 6:
            samples.append((row["code"], da, en, "ok"))

    print(f"Translated SOC_ger7 rows: {applied}")
    print(f"  with Danish characters still remaining: {leftover_danish}")
    print("\nSamples:")
    for code, da, en, kind in samples:
        print(f"  [{kind}] {code}")
        print(f"    DA: {da}")
        print(f"    EN: {en}")

    if args.dry_run:
        print("\n[dry-run] no changes written")
        return

    with open(MASTER_PATH, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)
    print(f"\nWrote {len(rows)} rows to {MASTER_PATH}")


if __name__ == "__main__":
    main()
